DROP TABLE IF EXISTS `pay_order`;
CREATE TABLE `pay_order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `order_no` varchar(200) DEFAULT NULL COMMENT '支付订单号',
  `out_order_no` varchar(200) DEFAULT NULL COMMENT '支付项目订单号',
  `total_fee` float(10,2) DEFAULT '0.00' COMMENT '支付金额',
  `body` varchar(200) DEFAULT NULL COMMENT 'descr',
	`attach` varchar(200) DEFAULT NULL COMMENT 'attach',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '购买时间',
  `create_user` int(11) DEFAULT NULL COMMENT '支付用户',
  `pay_time` int(11) DEFAULT NULL COMMENT '购买时间',
  `pay_way` varchar(20) DEFAULT NULL COMMENT 'ZFB、WX',
  `trade_type` varchar(20) DEFAULT NULL COMMENT 'ZFB、WX',
  `status` tinyint(2) DEFAULT '0' COMMENT '订单状态0=待支付，1=已支付，-1=支付异常',
  `trade_no` varchar(100) DEFAULT NULL COMMENT '第三方支付订单号',
  `spbill_create_ip` varchar(64) DEFAULT NULL COMMENT '支付ip',
  `notify_url` varchar(64) DEFAULT NULL COMMENT '回调地址',
  `queue_key` varchar(64) DEFAULT NULL COMMENT '队列key',
  `appid` varchar(64) DEFAULT NULL COMMENT 'appid',
  `mch_id` varchar(64) DEFAULT NULL COMMENT '商户id',
  `call_request_body` LONGTEXT DEFAULT NULL COMMENT '回调参数（JSON）',
	`group` varchar(64) DEFAULT NULL COMMENT '分组',
  PRIMARY KEY (`id`),
  KEY `create_time` (`create_time`) USING BTREE,
  KEY `order_no` (`order_no`) USING BTREE,
  KEY `out_order_no` (`out_order_no`) USING BTREE,
  KEY `create_user` (`create_user`) USING BTREE,
  KEY `pay_time` (`pay_time`) USING BTREE,
  KEY `pay_way` (`pay_way`) USING BTREE,
  KEY `trade_type` (`trade_type`) USING BTREE,
  KEY `trade_no` (`trade_no`) USING BTREE,
  KEY `group` (`group`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=100000076 DEFAULT CHARSET=utf8 COMMENT='支付订单';

